config/routes.rb
Tagorion::Application.routes.draw do

  resources :names do
    resources :tags
  end

  root 'welcome#index'
end

app/models/name.rb
class Name < ActiveRecord::Base
	has_many :tags, dependent: :destroy
	validates :namalengkap, presence: true, length: { minimum: 5}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :name
  validates :tagtext, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def new
  end

end

app/controllers/names_controller.rb
class NamesController < ApplicationController

	http_basic_authenticate_with name: "dhh", password: "burbank42", except:[:index, :show]

	def new
		@name = Name.new
	end

	def edit
		@name = Name.find(params[:id])
	end

	def index
		@names = Name.all
	end

	def show
		@name = Name.find(params[:id])
	end

	def create
		@name = Name.new(name_params)

		if @name.save
			redirect_to @name
		else
			render 'new'
		end
	end

	def update
		@name = Name.find(params[:id])

		if @name.update(name_params)
			redirect_to @name
		else
			render 'edit'
		end
	end

	def destroy
		@name = Name.find(params[:id])
		@name.destroy

		redirect_to names_path
	end

	private
		def name_params
			params.require(:name).permit(:namalengkap, :npm)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	http_basic_authenticate_with name: "dhh", password: "burbank42", only: :destroy

	def create
		@name = Name.find(params[:name_id])
		@tag = @name.tags.create(tag_params)
		redirect_to name_path(@name)
	end

	def destroy
		@name = Name.find(params[:name_id])
		@tag = @name.tags.find(params[:id])
		@tag.destroy
		redirect_to name_path(@name)
	end

	private
		def tag_params
			params.require(:tag).permit(:tagger, :tagtext)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbarh.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Orion 2014</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="../names/">Database Tag</a>
            </li>
            <li>
              <a href="../names/new">New Entry</a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><a href="https://wrapbootstrap.com/?ref=bsw" target="_blank">Built with WrapBootstrap</a></li>
          </ul>

        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <meta charset="utf-8">
  <title>Orion 2014</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../bower_components/html5shiv/dist/html5shiv.js"></script>
      <script src="../bower_components/respond/dest/respond.min.js"></script>
    <![endif]-->
    <script>

     var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23019901-1']);
      _gaq.push(['_setDomainName', "bootswatch.com"]);
        _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);

     (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

    </script>

</head>
<body>

<%= render 'layouts/navbarh' %>

<%= yield %>

</body>
</html>

app/views/names/_form.html.erb
<%= form_for @name do |f| %>
	<% if @name.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@name.errors.count, "error") %> prohibited this article from being saved: </h2>
		<ul>
		<% @name.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
	<% end %>

	<p>
		<%= f.label :namalengkap %><br>
		<%= f.text_field :namalengkap %>
	</p>

	<p>
		<%= f.label :npm %><br>
		<%= f.text_area :npm %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/names/edit.html.erb
<br>
<br>
<div class="container">
<h1>Edit Entry</h1>

<%= render 'form' %>

<footer>
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-unstyled">
    		  <li><br><%= link_to 'Back', names_path %></li>
    		  <li><br></li>
              <li><br></li>
            </ul>
            <p>Made by George A.P. with Ruby on Rails</p>
         </div>
    </div>
</footer>

</div>

app/views/names/index.html.erb
<div class="container">

<br><br><br>

<div class="bs-docs-section">

  <div class="row">
    <div class="col-lg-12">
     	<div class="page-header">
       	<h1 id="tables">Data Tag Angkatan</h1>
       		</div>

      <div class="bs-component">

			<table class="table table-hover">
				<thead>
					<tr>
						<th>Nama Lengkap</th>
						<th>Tags</th>
						<th>Link Photo</th>
						<th>Edit</th>
						<th>Destroy</th>
						</tr>
				</thead>

				<tbody>
					<% @names.each do |name| %>
						<tr>
							<td><%= link_to name.namalengkap, name_path(name) %></td>
							<td><%= link_to 'Tags', name_path(name) %></td>
							<td><%= link_to 'Photo', "../assets/#{name.npm}.jpg" %></td>
							<td><%= link_to 'Edit', edit_name_path(name) %></td>
							<td><%= link_to 'Destroy', name_path(name), method: :delete, data: { confirm: 'Are you sure you want to delete your name?'} %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			</div>
		</div>
	</div>

<footer>
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-unstyled">
    		  <li><br></li>
    		  <li><br></li>
              <li><a href="#top">Back to top</a></li>
              <li><br></li>
            </ul>
            <p>Made by George A.P. with Ruby on Rails</p>
         </div>
    </div>
</footer>

</div>

app/views/names/new.html.erb
<br>
<br>
<div class="container">

<h1>Entry Nama Baru</h1>

<%= render 'form' %>

<footer>
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-unstyled">
    		  <li><br><%= link_to 'Back', names_path %></li>
    		  <li><br></li>
              <li><br></li>
            </ul>
            <p>Made by George A.P. with Ruby on Rails</p>
         </div>
    </div>
</footer>

</div>

app/views/names/show.html.erb
<div class="container">

<div class="page-header" id="banner">
    <div class="row">
          <div class="col-lg-8 col-md-7 col-sm-6">
          	<br>
            <h1><%= @name.namalengkap %></h1>
          </div>
    </div>
</div>

<div class="jumbotron">
	<div class="container">
      <div class="row">
        <div class="col-md-5">
        	<%= image_tag "#{@name.npm}.jpg", size:"354x433" %>
        </div>

        <div class="col-md-7">
        	<h2><strong>Tags:</strong></h2>
			<% @name.tags.each do |tag| %>
			<h3><%= tag.tagtext %></h3><p style="font-size: 0.9em;"><i>tagged by <%= tag.tagger %></i><%= link_to '.', [tag.name, tag],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></p>
			<% end %>
        </div>
		</div>
	</div>
</div>

<h2>Add a tag:</h2>
<p>Tolong tulis juga nama yg add tag ke "Tagger."</p>
<%= form_for([@name, @name.tags.build]) do |f| %>
	<p>
		<%= f.label :tagger %><br>
		<%= f.text_field :tagger %>
	</p>
	<p>
		<%= f.label "Tag" %><br>
		<%= f.text_area :tagtext %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<br>
<br>
<p>Tags as String:</p>

<div class="panel panel-default">
  <div class="panel-body">
    <% @name.tags.each do |tag| %>
	<%= tag.tagtext %>,
	<% end %>
  </div>
</div>

<footer>
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-unstyled">
    		  <li><br></li>
    		  <li><br></li>
              <li><a href="#top">Back to top</a></li>
              <li><%= link_to 'Back', names_path %></li>
              <li><%= link_to 'Edit', edit_name_path(@name) %></li>
              <li><br></li>
            </ul>
            <p>Made by George A.P. with Ruby on Rails</p>
         </div>
    </div>
</footer>

</div>

app/views/tags/_formfield.html.erb
<% if @tag.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@tag.errors.count, "error") %> prohibited this article from being saved: </h2>
		<ul>
		<% @tag.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
	<% end %>

app/views/welcome/index.html.erb
<br>
<br>
<div class="container">
<h1>Data Tag Orion 2014</h1>
<%= link_to 'Database', controller: 'names' %>

<footer>
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-unstyled">
    		  <li><br></li>
    		  <li><br></li>
              <li><br></li>
            </ul>
            <p>Made by George A.P. with Ruby on Rails</p>
         </div>
    </div>
</footer>

</div>